#ifndef PINS_H
#define PINS_H

#define FOOTSWITCH_PIN_1 72
#define FOOTSWITCH_PIN_2 74
#define FOOTSWITCH_PIN_3 76
#define FOOTSWITCH_PIN_4 78

#define LED_PIN_1 71
#define LED_PIN_2 73
#define LED_PIN_3 75
#define LED_PIN_4 77

#define SEGMENT_A_PIN 36
#define SEGMENT_B_PIN 38
#define SEGMENT_C_PIN 40
#define SEGMENT_D_PIN 42
#define SEGMENT_E_PIN 52
#define SEGMENT_F_PIN 50
#define SEGMENT_G_PIN 54

#define BYPASS_TYPE_BUTTON_PIN 58
#define BYPASS_TYPE_LED_PIN 70
#define BYPASS_TYPE_RELAY_PIN 55

#define AMPSWITCH_BUTTON_PIN 60
#define AMPSWITCH_LED_PIN 53
#define AMPSWITCH_RELAY_PIN 59

#define BYPASS_RELAY_PIN 57

#define SPI_CHIP_SELECT 10

#endif // PINS_H