#ifndef PINS_H
#define PINS_H

#define FOOTSWITCH_PIN_1 2
#define FOOTSWITCH_PIN_2 3
#define FOOTSWITCH_PIN_3 4
#define FOOTSWITCH_PIN_4 5

#define LED_PIN_1 2
#define LED_PIN_2 3
#define LED_PIN_3 4
#define LED_PIN_4 5

#define SEGMENT_A_PIN 7
#define SEGMENT_B_PIN 6
#define SEGMENT_C_PIN 5
#define SEGMENT_D_PIN 11
#define SEGMENT_E_PIN 10
#define SEGMENT_F_PIN 8
#define SEGMENT_G_PIN 9

#define AMPSWITCH_BUTTON_PIN 44
#define AMPSWITCH_LED_PIN 45
#define AMPSWITCH_RELAY_PIN 48

#define BYPASS_BUTTON_PIN 46
#define BYPASS_LED_PIN 47
#define BYPASS_RELAY_PIN 49

#endif // PINS_H