#ifndef PINS_H
#define PINS_H

#define FOOTSWITCH_PIN_1 28
#define FOOTSWITCH_PIN_2 26
#define FOOTSWITCH_PIN_3 24
#define FOOTSWITCH_PIN_4 22

#define LED_PIN_1 29
#define LED_PIN_2 27
#define LED_PIN_3 25
#define LED_PIN_4 23

#define SEGMENT_A_PIN 48
#define SEGMENT_B_PIN 46
#define SEGMENT_C_PIN 44
#define SEGMENT_D_PIN 42
#define SEGMENT_E_PIN 40
#define SEGMENT_F_PIN 38
#define SEGMENT_G_PIN 36

#define BYPASS_TYPE_BUTTON_PIN 32
#define BYPASS_TYPE_LED_PIN 39
#define BYPASS_TYPE_RELAY_PIN 35

#define AMPSWITCH_BUTTON_PIN 30
#define AMPSWITCH_LED_PIN 37
#define AMPSWITCH_RELAY_PIN 31

#define BYPASS_RELAY_PIN 33

#define SPI_CHIP_SELECT 10

#define FADER_BOOST_MOTOR_A_PIN 100
#define FADER_BOOST_MOTOR_B_PIN 101
#define FADER_BOOST_TOUCH_SENSOR_PIN 102
#define FADER_BOOST_WIPER_PIN 102

#define FADER_BASS_MOTOR_A_PIN 100
#define FADER_BASS_MOTOR_B_PIN 101
#define FADER_BASS_TOUCH_SENSOR_PIN 102
#define FADER_BASS_WIPER_PIN 102

#define FADER_MIDDLE_MOTOR_A_PIN 100
#define FADER_MIDDLE_MOTOR_B_PIN 101
#define FADER_MIDDLE_TOUCH_SENSOR_PIN 102
#define FADER_MIDDLE_WIPER_PIN 102

#define FADER_TREBLE_MOTOR_A_PIN 100
#define FADER_TREBLE_MOTOR_B_PIN 101
#define FADER_TREBLE_TOUCH_SENSOR_PIN 102
#define FADER_TREBLE_WIPER_PIN 102

#define FADER_CUT_MOTOR_A_PIN 100
#define FADER_CUT_MOTOR_B_PIN 101
#define FADER_CUT_TOUCH_SENSOR_PIN 102
#define FADER_CUT_WIPER_PIN 102

#endif // PINS_H